### PR TITLE
Add svg & png versions of a hexagon badge.

### PR DESCRIPTION
**Pull request by tzmanics**
svg hex measures 5.08cm from top to bottom.
png hex is just big.

### CODE REVIEW

**Comment by bcomnes** [comment]
Awesome!  Should we add these to .npmignore so it doesn't accidentally get pushed to npm?

**Comment by yoshuawuyts** [comment]
✨✨✨ wonderful. Yeah, not publishing to npm would be a good move hah.

**Comment by tzmanics** [comment]
np, I'm not seeing a `.npmignore` though do you want me to make one or should I add it to the `.gitignore`? Also, do you want me to add the other badge too?

**Comment by tzmanics** [comment]
went ahead and added the `.npmignore`, ignoring all png & svg files

**Comment by bcomnes** [comment]
@tzmanics Cool this looks good to go.

**Comment by dcousens** [comment]
@tzmanics did you see https://cloud.githubusercontent.com/assets/121766/11316733/02ade7b0-8fc8-11e5-88f9-8858213841ab.png?

**Comment by bcomnes** [comment]
I'm for collecting all the logos!

**Comment by tzmanics** [comment]
@dcousens Yea! Do you want me to add it to this PR?
I could also make a `logos` dir and add them all (+ reflect the change in the .npmignore) :yum:

**Comment by maxogden** [comment]
HI TARA. that is all

On Monday, November 23, 2015, Tara Z. Manicsic <notifications@github.com>
wrote:

> @dcousens <https://github.com/dcousens> Yea! Do you want me to add it to
> this PR?
> I could also make a logos dir and add them all (+ reflect the change in
> the .npmignore) [image: :yum:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feross/standard/pull/336#issuecomment-159125010>.
>


-- 
Sent from my phone

**Comment by bcomnes** [comment]
+1 to the logos folder

**Comment by dcousens** [comment]
Thoughts @feross?

**Comment by tzmanics** [comment]
here is it. I'll revert if you want it done differently nbd.

**Comment by dcousens** [comment]
@feross got an SVG?

**Comment by feross** [comment]
Don't move `badge.png` and `badge.svg` from the root into `logos/`, or everyone's readme badges will break!

**Comment by feross** [comment]
SVG for my badge is here:

```
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg width="100%" height="100%" viewBox="0 0 181 209" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:1.41421;"><g id="logo"><path id="template_outline" d="M0,51.944l90.197,-51.944l90.198,51.944l0.605,105.112l-90.197,51.944l-90.803,-51.944l0,-105.112Z" style="fill:#f3df49;"/><path id="j" d="M46.032,150.054l13.192,-8.06c2.545,4.556 4.861,8.41 10.414,8.41c5.323,0 8.679,-2.102 8.679,-10.279l0,-55.605l16.2,0l0,55.837c0,16.938 -9.835,24.648 -24.185,24.648c-12.959,0 -20.482,-6.775 -24.3,-14.952" style="fill:#2e2e2c;"/><path id="s" d="M103.316,148.302l13.191,-7.71c3.472,5.724 7.985,9.93 15.969,9.93c6.713,0 10.993,-3.388 10.993,-8.061c0,-5.607 -4.397,-7.593 -11.803,-10.863l-4.049,-1.754c-11.688,-5.022 -19.441,-11.33 -19.441,-24.647c0,-12.266 9.257,-21.612 23.722,-21.612c10.299,0 17.704,3.622 23.027,13.084l-12.613,8.177c-2.778,-5.023 -5.786,-7.009 -10.414,-7.009c-4.744,0 -7.753,3.038 -7.753,7.009c0,4.906 3.009,6.893 9.951,9.93l4.05,1.752c13.77,5.958 21.523,12.032 21.523,25.699c0,14.72 -11.456,22.78 -26.845,22.78c-15.044,0 -24.764,-7.242 -29.508,-16.705" style="fill:#2e2e2c;"/><text x="24.297px" y="72.286px" style="font-family:Neutra Text;font-size:35px;font-weight:700;fill:#2e2e2c;">s<tspan x="38.507px 52.227px " y="72.286px 72.286px ">ta</tspan>ndar<tspan x="137.417px " y="72.286px ">d</tspan></text></g></svg>
```

Can't attach it to the issue, so maybe @tzmanics can add it to this PR?

**Comment by tzmanics** [comment]
@feross yikes, reverted & fixed that! The standard-hex svg required the neutra text font, I fixed it, hope that's cool.

**Comment by feross** [comment]
Forgot to merge this – it's merged now!

**Comment by tzmanics** [comment]
Yay! Super stoked to get all these hex Standard stickers! Let me know if you need any other help!

**Pull request merged**
