### PR TITLE
eslint@~3.6.0

### PR DESCRIPTION
**Pull request by LinusU**
Skimmed thru the changelog and it looks good ð 

https://github.com/eslint/eslint/blob/v3.6.0/CHANGELOG.md

@feross Is there any manual testing that I should do?

### CODE REVIEW

**Comment by LinusU** [comment]
Fails because of jprichardson/is-electron-renderer#5

**Comment by dcousens** [comment]
ping @jprichardson,  you're holding up progress in the universe :smiley:

**Comment by jprichardson** [comment]
Ahhh! Sorry guys, I'm on it right now!

**Comment by jprichardson** [comment]
The universe can continue now 😝

**Comment by LinusU** [comment]
(closing and opening to retrigger Travis)

**Pull request merged**
