### PR TITLE
switch to standard-engine

### PR DESCRIPTION
**Pull request by Flet**
This PR will switch `standard` to use `standard-engine`.

`standard-engine` is a package I've been keeping synced up with `standard`. It includes only the "engine" bits and none of the rules. We're using it currently on `semistandard` to keep it synced up without a lot of hassle. Its also used on `doublestandard` too :)

This PR points to a prerelease version of `standard-engine@2.0.0-1` which is using `eslint@1.0.0-rc-1`, so it should work out nicely to be part of `5.0.0` if thats possible.

There are some slight differences in the CLI `--help` text. We can change `standard-engine` if folks wish.

All collaborators from here have been added to `standard-engine` and are free to treat it with the same care as `standard` :) Also, all git commits from `standard` were preserved, so contributions should still be reflected there too.

Anyone have thoughts on this?

### CODE REVIEW

**Comment by Flet** [comment]
This should also close #87 if its accepted

**Comment by Flet** [comment]
...just realized deps need tobbe cleaned up now

**Comment by dcousens** [comment]
I've used standard-engine myself in https://github.com/JedWatson/happiness,  so I'm pro this idea.

**Comment by Flet** [comment]
Synced up `standard` with `standard-engine@2` and picked apart `cli.js` and `index.js` and got them much closer to `standard` now. 

Dependencies should be a lot better now.

**Comment by Flet** [comment]
Sweet! Now I guess I should make the `standard-engine` README a little better...

**Comment by feross** [comment]
Thanks, this is now merged! I made a few fixes in `standard-engine` and re-locked the dependencies that you loosed in `package.json`. It's a lot easier to debug issues that come up when dependencies aren't shifting. And we're currently doing pretty regular releases, so I'm not worried about people not getting bugfixes :)

**Comment by Flet** [comment]
Excellent! :+1: 

Thanks! Makes sense to lock things down. And thanks for finding those bits I missed.

**Comment by feross** [comment]
No problem. Really happy that we can share the effort here and you don't have to manually keep things in sync anymore.

**Comment by feross** [comment]
Released as 5.0.1.

**Pull request merged**
