### PR TITLE
README.md: WebStorm/PhpStorm support

### PR DESCRIPTION
**Pull request by jelz**
This (hopefully) fixes feross/standard#247

Before merging: dear WebStorm/PhpStorm users, can you try to reproduce my steps and share an outcome here?

### CODE REVIEW

**Comment by rstacruz** [comment]
@feross, it might be time to have a `docs/` folder for standard to refactor the ever-growing `README.md`.

```
docs/editor-integration.md
docs/webstorm.md
docs/formatter.md
...
```

**Comment by feross** [comment]
These instructions are currently too long to add to the middle of the current readme.

@jelz Can you create a `docs/` folder and put these into a `webstorm.md` file that's linked from the readme?

**Comment by jelz** [comment]
@feross If you wish I can extract all IDE/editor support docs (not only my WebStorm instruction) into separate files.

Either way I'll take care of this PR tomorrow in the evening or during the weekend, depending on my workload.

**Comment by feross** [comment]
Let's leave the other editor's instructions where they are since they're pretty short. I like that most users can follow the instructions without needing to go to any other pages.

Thanks - looking forward to your updated PR.

**Comment by jelz** [comment]
Updated and rebased onto `master`.

**Comment by feross** [comment]
LGTM. Thanks!

**Pull request merged**
