### PR TITLE
added self, importScripts and close to globals

### PR DESCRIPTION
**Pull request by reg4in**
Battles the problem described in #75.

### CODE REVIEW

**Comment by JakeChampion** [comment]
I think this may be a bug in eslint.

``` JS
// worker.js
importScripts('../../pouchdb.min.js')
const db = new PouchDB('example')
```
If you run this file through `standard`, it returns 
``` BASH
worker.js:3:0: 'PouchDB' is not defined.
```

**Comment by calvinmetcalf** [comment]
so there are 2 related issues, the first is that standard would like you to always use the global object when referring to globals, aka in the browser you'd go window.foo = PouchDB

BUT in web workers the global object is named self which conflicts with the rule which says that you always have to do `var self = this` 

but tl;dr from #11 do 

```js
//worker.js
/* global self */
self.importScripts('../../pouchdb.min.js')
const db = new self.PouchDB('example')
```

**Comment by reg4in** [comment]
Oops forgot about that `var self = this` thing ...

**Comment by feross** [comment]
Yeah, this is a tough one. We want to prevent accidental use of the browser's unfortunately named `window.self` variable, which is why `self` is not added as a global.

Right now, I recommend you add `/*global self */` to the top of web workers and service workers to fix the `standard` errors and be extra explicit that you expect this file to be run as a Worker. I agree with you that this is not ideal, but I think it's the best we can do at the moment. We can revisit this later when/if there's a better solution.

Thanks for opening the original issue and sending this PR :)

**Comment by maxogden** [comment]
I documented this in the readme https://github.com/feross/standard/blob/master/README.md#what-about-web-workers

**Comment by feross** [comment]
Thanks @maxogden!

**Pull request closed without merging**
