### PR TITLE
Add two new badge designs

### PR DESCRIPTION
**Pull request by feross**
Guys, what do you think of these designs?

### CODE REVIEW

**Comment by feross** [comment]
standard-outline

standard-outline-white

**Comment by maxogden** [comment]
+1

**Comment by dcousens** [comment]
NACK,  these are sticker designs.  IMHO the badge should still be the square.

**Comment by feross** [comment]
@dcousens Yep, that's what I meant.

**Comment by rstacruz** [comment]
definetely better.

**Comment by dcousens** [comment]
:+1:

**Pull request merged**
