### PR TITLE
ESLint no-dupe-args rule

### PR DESCRIPTION
**Pull request by mightyiam**
Not yet released.
https://github.com/eslint/eslint/commit/64cdf9e8ad73032d7831dd96ecb539cfe1e1d485.

### CODE REVIEW

**Comment by feross** [comment]
What happens if you include a rule that is not recognized? Should we wait
until release before merging?

**Comment by mightyiam** [comment]
I don't know, @feross, so I would just wait for next release and check whether the rule is indeed in it.

Are you following releases?

**Comment by feross** [comment]
Yep, I'm bumping the eslint dep anytime I notice it's out of date. If you notice a release and we haven't updated yet, please comment here or open a new issue.

**Comment by Flet** [comment]
Looks like travis answered your question: throws error if rule is not found. :)

**Comment by feross** [comment]
This PR is included in `standard@3.0.0-beta`.

**Comment by mightyiam** [comment]
Thank you!

**Pull request closed without merging**
