### PR TITLE
Make example run standard after tests have passed

### PR DESCRIPTION
**Pull request by motdotla**
Loving standard, @feross. Even the lack of semi-colons.

The only thing I found in my flow - especially switching to standard was:

I prefer to see format run AFTER my tests. This way, I'm focused on getting code to pass first and format second. 

This pull request just updates the README to reflect that personal opinion.

Sooo, this is an extremely nitpicky and mostly personal pull request, but I thought the majority might have a similar flow of programming thought. :smile_cat:

### CODE REVIEW

**Comment by dcousens** [comment]
This is just an example though?  No?

**Comment by motdotla** [comment]
Exactly. Just an example. 




A lot of people will likely just copy and paste the example. I'd argue it'd be better they copy and paste with it at the end. 




Like I said, super nitpicky here and one of the least worthwhile pull requests I've done. But it's late and I'm at a hackathon so maybe not the clearest thinking either right now.

**Comment by feross** [comment]
Thanks for the PR. I actually like having `standard` run first because it only takes 1-2 seconds, while the rest of my tests frequently take 1-2 minutes (remote browser tests are slow). I'd rather fail early than late.

**Comment by motdotla** [comment]
Cool cool.

**Pull request closed without merging**
