### PR TITLE
Remove standard-format. fixes #340

### LINKED ISSUE #340: Move standard --format into a separate module
Currently around ~1/3 of the dependencies are there to support `standard --format`. I propose we move that command to a separate module `standard-format` since it isn't related to linting and would make standard a lot "lighter" to install.

### PR DESCRIPTION
**Pull request by mafintosh**
With this PR standard has around 250 fewer dependencies when installing.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
haha, lgtm :sparkles:

**Comment by dcousens** [comment]
@mafintosh does this break `standard --format`?

**Comment by feross** [comment]
@dcousens Yes, it will. We're going to recommend that folks install `standard-format` separately from now on. The dependencies for `standard-format` are just too many and it makes install take way too long, even more-so with npm 3.

**Comment by feross** [comment]
@mafintosh This looks good, but I want to print a friendlier message to people who try to run `standard --format`. Maybe something like:

```
Code formatting is available in a standalone package: "standard-format". To install it, run "npm install -g standard-format".
```

**Comment by dcousens** [comment]
ACK :+1:

**Comment by feross** [comment]
This has been merged into the `v6` branch.

**Pull request closed without merging**
