### PR TITLE
Add example of usage within npm scripts

### PR DESCRIPTION
**Pull request by timoxley**
Related https://github.com/feross/standard/pull/621#issuecomment-247145748

### CODE REVIEW

**Comment by feross** [comment]
Thanks for sending this, but I liked the old wording ("what you might do if you're clever"), even though it's technically less informative in the ToC. And also the list format made the steps clearer.

**Comment by timoxley** [comment]
@feross Updated. Moved it as-is.

**Comment by feross** [comment]
Thanks!! Sorry for being a nitpick ;)

**Comment by timoxley** [comment]
not at all an issue.

**Pull request merged**
