### PR TITLE
Rules: add note about var assignments

### PR DESCRIPTION
**Pull request by rstacruz**
documents the `one-var` rule

### CODE REVIEW

**Comment by Flet** [comment]
:+1: 

We may also want to point out that its OK to put uninitialized vars on the same line:

```js
// ✓ ok
var x, y, z
```

**Comment by dcousens** [comment]
LGTM, can't merge until CI passes

**Comment by feross** [comment]
Passing now, thanks to @flet :)

**Comment by feross** [comment]
merged.

**Pull request merged**
