### PR TITLE
Add Emacs to the list of supported editors

### PR DESCRIPTION
**Pull request by lvillani**

### CODE REVIEW

**Comment by lvillani** [comment]
@lunaryorn Is this correct?

**Comment by lunaryorn** [comment]
No.  Please don't suggest to alter `flycheck-checkers`.  Users should use `flycheck-checker` via directory variables to select a checker per project, or `flycheck-disabled-checkers` to disable undesired syntax checkers locally or globally.  See the manual for details.

**Comment by feross** [comment]
Lmk once you've worded this correctly and we can merge it.

**Comment by lvillani** [comment]
@lunaryorn I removed any mention of `flycheck-checkers`.

**Comment by feross** [comment]
Merged - thanks! :)

**Comment by lunaryorn** [comment]
Thank you!

**Pull request merged**
