### PR TITLE
add readme & rules in spanish

### PR DESCRIPTION
**Pull request by falmar**
I've in the need to share this repository/package with my coworkers and few people of which some of them does not speak English. And I though would be nice to make this contribution. So this repo could reach by more people in Spanish spoken community.

I appreciate any feedback.

Thanks

### CODE REVIEW

**Comment by feross** [comment]
YES! This is so excellent! I'm so stoked to merge this, as well as any other language translations that people want to submit.

Thanks @falmar!

**Comment by Flet** [comment]
👍 Now live on [standardjs.com](http://standardjs.com)

**Comment by Flet** [comment]
OK, I made a small update to `standard-www` and now the alternate languages are live on [standardjs.com](http://standardjs.com) The site nav is still in english though :/

**Comment by falmar** [comment]
Oh I see... Thanks for accepting @feross ... I'll probably give it a review again to find and fix any typo or grammar mistakes.

@Flet I just took a peek into `standard-www`. I never used the `markdown-styles` but is it possible or easy to change the nav bar according to the language or would that require a huge refactor for it?

**Comment by feross** [comment]
Oh I just noticed that we're missing a link to the Spanish translation in RULES.md. I'll send a PR.

**Comment by Flet** [comment]
@falmar it shouldn't be too difficult. I think there might be a more efficient way of dealing with multiple languages that makes adding new languages easier...

Maybe have each one as a sub directory like http://standardjs.com/esla/index.html

It may be easier to accomplish this if we rework the /docs directory to have a directory for each language instead (and we could include a nav file in the native language as well).

Something like: 
```
└── docs
    ├── esla
    │   ├── README.md
    │   └── RULES.md
    └── pbtr
        ├── README.md
        └── RULES.md
```

...we could also update the site generation to automatically build the links to each translation. This could be good if @feross wants to make a wider call for translations.. we could add them quickly to the site by just rebuilding.

**Comment by feross** [comment]
@Flet I don't think it's too bad to maintain the inline links manually for now, especially since we're only linking back to the English version from the translations. As for the navigation links, I'm happy to do whatever you think is best.

**Comment by feross** [comment]
I just tweeted about how we're looking for more translations! https://twitter.com/feross/status/822568452330291201

**Pull request merged**
