### PR TITLE
support app node_modules

### PR DESCRIPTION
**Pull request by ahdinosaur**
i implemented option 1 from #61: "we could ignore node_modules if a package.json is present in the same directory".

rough sketch of changes (feedback appreciated):
- removed the `**/node_modules/**` ignore pattern
- added `**/package.json` to the search patterns and also to the ignore patterns
- before ignore, iterate over list of files matched by search pattern and if it is a `package.json`, add `join(basename(file), 'node_modules/**)'` to the ignore patterns
- change order of de-duping files and regexifying ignore patterns

### CODE REVIEW

**Comment by feross** [comment]
I just merged branch `v3` into `master` and published `v3.0.0`. Can you rebase and update this PR? I simplified the way that `glob` is used here: https://github.com/feross/standard/commit/b03bcc34dbc23efbc0d2becae88f09e29b12a006 so your code will require some changes.

**Comment by feross** [comment]
Hey @ahdinosaur, if you still want to work on fixing up this PR, please now rebase against the `speed` branch, as that will become the new `master` in a few days and it makes significant changes.

**Comment by ahdinosaur** [comment]
@feross sweet, thanks for the heads up. i'm still keen to fix this PR, just considering the best approach to do it now with the new and improved code, mostly due to the lack of separate search and filter steps which i relied on.

**Comment by feross** [comment]
Hey Mikey :) It was nice to meet you in NZ!

**Comment by ahdinosaur** [comment]
@feross likewise, i'm really glad to be able to associate a human to the bits and pixels. thanks for being awesome. :smile_cat:

regarding this PR, i'm stalling on it because the only solution i can imagine feels so hacky and wrong: do a pre-search to find `package.json` files so you can add those directories' `node_modules` to the list of ignores.

i'm not sure how best to resolve this. it seems like the only sensible way to handle the app modules pattern without crazy hacks is to by default only ignore `/node_modules`, and maybe support [other ignores](https://github.com/feross/standard/pull/35) through https://github.com/feross/standard/issues/95 and the `package.json` fields, but i'm not sure if that's acceptable for this project.

**Comment by ngoldman** [comment]
My 2 cents: reading #61 and #95 it seems like the best option is to respect `.gitignore` and let it do the work of sorting out what should and shouldn't be ignored by `standard` beyond root `node_modules`.

**Comment by feross** [comment]
Yeah, I think respecting `.gitignore` makes the most sense. PR out: https://github.com/feross/standard/pull/107

**Comment by feross** [comment]
Closing this now, since .gitignore support is released in 3.4.0, and the default `**/node_modules/**` ignore was changed to `node_modules/**`.

**Comment by ahdinosaur** [comment]
sweet, thanks @feross!

**Comment by feross** [comment]
No problem! :-)

**Pull request closed without merging**
