### PR TITLE
readme: suggest cleverer npm scripts integration

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
This is what I did so far and I love it.

**Comment by jprichardson** [comment]
This is also the convention I have adopted as well. This way I can run `lint` on Travis by itself.

**Comment by dcousens** [comment]
Concept ACK, this is also what I do

**Comment by feross** [comment]
I think either way is fine, but for the readme example I prefer it the current (simpler) way.

**Pull request closed without merging**
